blog/urls.py
from django.urls import path, re_path
from . import views

# namespace
app_name = 'blog'

urlpatterns = [
    path("", views.PostLV.as_view(), name="index"),
    # 위랑 같은 페이지, 주소만 다름
    path("post/", views.PostLV.as_view(), name="post_list"),
    # # slug가 한글이면 <slug:slug> 했을 때 오류남
    # path("post/<slug:slug>", views.PostDV.as_view(), name="post_detail"),
    re_path(r'post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name="post_detail"),

    # Example: /blog/archive/
    path('archive/', views.PostAV.as_view(), name='post_archive'),

    # Example: /blog/archive/2019/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),

    # Example: /blog/archive/2019/nov/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),

    # Example: /blog/archive/2019/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),

    # Example: /blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),

    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),

    path('search/', views.SearchFormView.as_view(), name='search'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from config.views import HomeView, UserCreateView, UserCreateDoneTV
from django.conf.urls.static import static
from django.conf import settings
from config.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path('admin/', admin.site.urls),
    path("bookmark/", include("bookmark.urls")),
    path("blog/", include("blog.urls")),
    path("photo/", include("photo.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/register/", UserCreateView.as_view(), name='register'),
    path('accounts/register/done/',UserCreateDoneTV.as_view(), name='register_done'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager

class Post(models.Model):
    # CharField(max_length) 지정해야 에러 안남
    title = models.CharField(verbose_name='TITLE', max_length=50)
    # slug : 제목 별칭
    slug = models.SlugField(verbose_name="SLUG", unique=True, allow_unicode=True, help_text="one word for title alias.")
    description = models.CharField("DESCRIPTION", max_length=100, blank=True, help_text="simple text")
    content = models.TextField("CONTENT")
    # 생성일
    create_dt = models.DateTimeField("CREATE DATE", auto_now_add=True)
    # 수정일
    modify_dt = models.DateTimeField("MODIFY DATE", auto_now=True)
    # 태그
    tags = TaggableManager(blank=True)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'blog_posts'
        ordering=('-modify_dt',)  # - : 내림차순(최신내용 맨 위)

    def __str__(self):
        return self.title
    # 메소드가 정의된 객체를 지칭하는 url 반환
    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.slug, ))
    # get_previous메소드 : 장고 내장 함수 호출. modify_dt를 기준으로 최신 포스트를 먼저 보여줌
    def get_previous(self):
        return self.get_previous_by_modify_dt()
    # get_previous메소드 : 장고 내장 함수 호출.modify_dt를 기준으로 다음 포스트 반환
    def get_next(self):
        return self.get_next_by_modify_dt()
    
# # Comment
# class Comment(models.Model):
#     # user <- 사용자테이블 있을 때
#     post = models.ForeignKey(Post, on_delete=models.CASCADE)
#     Comment = models.CharField(max_length=200)

blog/forms.py
from django import forms

class PostSearchForm(forms.Form):
    search_word = forms.CharField(label="Search Word")
    # date_val = forms.DateField(label="날짜정보")

blog/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from .models import Post
from django.views.generic import ListView, DetailView, ArchiveIndexView, YearArchiveView, MonthArchiveView, DayArchiveView, TodayArchiveView, TemplateView, FormView
from django.conf import settings
from blog.forms import PostSearchForm
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin

# ListView : 전체적인 데이터 보여줌
class PostLV(LoginRequiredMixin, ListView):
    model = Post
    # 템플릿 연결
    template_name = "blog/post_all.html"  # default : blog/post_list.html
    # 보여줄 객체
    context_object_name = 'posts'
    # 내용 한개를 한 페이지로 구성
    paginate_by = 3
    # 로그인 화면으로 연결(필수x)
    login_url = '/accounts/login/'
    # # 데이터 가져오기 (필터링 가능 ex)최근 5개 데이터 가져오기)
    # def get_queryset(self):
    #     return Post.objects.all()
    
# # PostLV 와 같은 기능   
# def dumppy_post(request):
#     object = Post.objects.all()
#     context = {
#         'posts' : object
#     }
#     return render(request, 'blog/post_all.html', context)


# DetailView : 특정 항목 하나를 보여줌
class PostDV(DetailView):
    model = Post
    # 템플릿 연결
    template_name = "blog/post_detail.html"
    # get_queryset -> get_object에서 id나 pk나 가져옴
    # def get_object(self):pass
    # DISQUS 데이터 보내기
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['disqus_short'] = f"{settings.DISQUS_SHORTNAME}"
        context['disqus_id'] = f"post-{self.object.id}-{self.object.slug}"
        context['disqus_url'] = f"{settings.DISQUS_MY_DOMAIN}{self.object.get_absolute_url()}"
        context['disqus_title'] = f"{self.object.slug}"
        return context


#--- ArchiveView
class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'modify_dt'
    template_name = "blog/post_archive.html"


class PostYAV(YearArchiveView):
    model = Post
    date_field = 'modify_dt'
    make_object_list = True
    template_name = "blog/post_archive_year.html"


class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'modify_dt'
    template_name = "blog/post_archive_month.html"


class PostDAV(DayArchiveView):
    model = Post
    date_field = 'modify_dt'
    template_name = "blog/post_archive_day.html"


class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_dt'
    template_name = "blog/post_archive_day.html"


# TAG
class TagCloudTV(TemplateView):
    template_name="taggit/taggit_cloud.html"

class TaggedObjectLV(ListView):
    template_name='taggit/taggit_post_list.html'
    model = Post
    def get_queryset(self):
        return Post.objects.filter(tags__name=self.kwargs.get('tag'))
    # post_list.html에 넘겨줄 컨텍스트 변수 추가하는 메소드
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tagname'] = self.kwargs['tag']
        return context
    

# SEARCH
class SearchFormView(FormView):
    form_class = PostSearchForm
    template_name = 'blog/post_search.html'

    def form_valid(self, form: Any) -> HttpResponse:
        # 검색어 확인
        searchWord = form.cleaned_data['search_word']
        # Q를 통해 검색하고
        post_list = Post.objects.filter(Q(title__icontains=searchWord) | Q(description__icontains=searchWord) | Q(content__icontains=searchWord)).distinct()
        # 결과를 담아
        context = {}
        context['form'] = form
        context['search_term'] = searchWord
        context['object_list'] = post_list
        # 페이지에 전달
        return render(self.request, self.template_name, context)

blog/templates/blog/post_all.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Post All{% endblock %}

{% block content %}

<br>

<h3>BLOG POST LIST</h3>

<br>
<div class="row">
{% for post in posts %}
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">{{ post.title | truncatechars:13}}</h5>
            <h6 class="card-subtitle mb-2 text-body-secondary">{{post.content | truncatechars:20}}</h6>
            <p class="card-text">{{post.modify_dt | date:"Y년 N d일" }}  </p>
            <a href="{% url 'blog:post_detail' post.slug %}" class="card-link">Detail</a>
        </div>
    </div>
{% endfor %}
</div>

<br>

<nav aria-label="Page navigation example">
  <ul class="pagination">
      {% if page_obj.has_previous %}
      <li class="page-item">
          <a href="?page={{ page_obj.previous_page_number }}" class="page-link">Previous</a>
      </li>
      {% else %}
      <li class="page-item disabled">
          <a href="#" class="page-link">PreviousPage</a>
      </li>
      {% endif %}
      <li class="page-item"><a class="page-link" href="#">Page {{ page_obj.number }} of {{page_obj.paginator.num_pages }}</a></li>

      {% if page_obj.has_next %}
      <li class="page-item">
          <a href="?page={{ page_obj.next_page_number }}" class="page-link">Next</a>
          {% else %}
      <li class="page-item disabled">
          <a href="#" class="page-link">NextPage</a>
      </li>
      </li>
      {% endif %}
  </ul>
</nav>

{% endblock %}

blog/templates/blog/post_archive.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Bookmark App{% endblock %}

{% block content %}

<h1>Archive List {% now "Y m d" %}</h1>

<ul>
    {% for date in date_list %}
    <li style="display: inline;"><a href="{% url 'blog:post_year_archive' date|date:'Y' %}"> Year-{{date|date:'Y'}} </a></li>
    {% endfor %}
</ul>

<br>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{post.modify_dt | date:"Y-m-d"}}
            <a href="{{post.get_absolute_url}}">{{post.title}}</a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

blog/templates/blog/post_archive_day.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Bookmark App{% endblock %}

{% block content %}

<h1>Post Archive for {{ day|date:"N d, Y" }}</h1>

<div>
  <ul>
      {% for post in object_list %}
      <li>{{post.modify_dt | date:"Y-m-d"}}
          <a href="{{post.get_absolute_url}}"><strong>{{post.title}}</strong></a>
      </li>
      {% endfor %}
  </ul>
</div>
{% endblock %}

blog/templates/blog/post_archive_month.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Bookmark App{% endblock %}

{% block content %}

<h1>Post Archive for {{ month|date:"N, Y" }}</h1>

<div>
  <ul>
      {% for post in object_list %}
      <li>{{post.modify_dt | date:"Y-m-d"}}
          <a href="{{post.get_absolute_url}}"><strong>{{post.title}}</strong></a>
      </li>
      {% endfor %}
  </ul>
</div>
{% endblock %}

blog/templates/blog/post_archive_year.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Bookmark App{% endblock %}

{% block content %}

<h1>Post Archives for {{year|date:"Y"}}</h1>

<ul>
    {% for date in date_list %}
    <li style="display: inline;"><a href="{% url 'blog:post_month_archive' date|date:'Y' date|date:'b'%}"> Year-{{date|date:'F'}}</a></li>
    {% endfor %}
</ul>

{# m : 04, F : April, M : Apr, b : apr #}

<br>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{post.modify_dt | date:"Y-m-d"}}
            <a href="{{post.get_absolute_url}}">{{post.title}}</a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Post Detail{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-8 mx-auto">
            <h1 class="mb-4">{{ post.title }}</h1>
            <p class="text-muted">게시일: {{ object.modify_dt|date:"j F Y" }}</p>
            <div class="post-content mt-4">
                {{ object.content|linebreaks }}
         </div>
    </div>
</div>    

<br>

<!-- DISQUS -->
<div id = "disqus_thread">

<!-- TAG -->
<!-- <div>
    <b>TAGS</b> <i class="fas fa-tag"></i>
    {% load taggit_templatetags2_tags %}
    {% get_tags_for_object object as "tags" %}
    {% for tag in tags %}
    <a href="{% url 'blog:tagged_object_list' tag.name %}">{{tag.name}}</a>
    {% endfor %}
&emsp;
    <a href="{% url 'blog:tag_cloud' %}"> <span class="btn btn-info btn-sm">TagCloud</span> </a>
</div> -->
{% endblock %}

{% block extra-script %}
<script>
    /**
    *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION
    *  BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
    *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT:
    *  https://disqus.com/admin/universalcode/#configuration-variables*/

    var disqus_config = function () {
        this.page.identifier = '{{ disqus_id }}';
        this.page.url = '{{ disqus_url }}';
        this.page.title = '{{ disqus_title }}';
    };

    (function() { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = 'https://{{ disqus_short }}.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
{% endblock %}

blog/templates/blog/post_search.html
{% extends "base.html" %}

{% block title %}Post_Search.html{% endblock %}

{% block content %}
<br>
<h1>Blog Search</h1>
<br>
<!--post 방식으로 view에 전달-->
<form action="." method="post">
    {% csrf_token %}
    {{form.as_table}}
    <input type = "submit" value="검색" class="">
</form>

<br>

{% if object_list %}
    {% for post in object_list %}
        <h2><a href="{{post.get_absolute_url}}">{{post.title}}</a></h2>
        {{post.modify_date|date:"Y N d"}}
        <p>{{post.content}}</p>
    {% endfor %}    
{% elif search_term %}
    <b>Search Word <i>{{search_term}}</i>으로 검색했는데 안나왔어요</b>
{% endif %}
{% endblock %}