blog/urls.py
from django.urls import path, re_path
from . import views

# namespace
app_name = 'blog'

urlpatterns = [
    path("", views.PostLV.as_view(), name="index"),
    # 위랑 같은 페이지, 주소만 다름
    path("post/", views.PostLV.as_view(), name="post_list"),
    # # slug가 한글이면 <slug:slug> 했을 때 오류남
    # path("post/<slug:slug>", views.PostDV.as_view(), name="post_detail"),
    re_path(r'post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name="post_detail"),

    # Example: /blog/archive/
    path('archive/', views.PostAV.as_view(), name='post_archive'),

    # Example: /blog/archive/2019/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),

    # Example: /blog/archive/2019/nov/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),

    # Example: /blog/archive/2019/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),

    # Example: /blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),

    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),

    path('search/', views.SearchFormView.as_view(), name='search'),
]

bookmark/urls.py
from django.urls import path
from . import views

# namespace
app_name = 'bookmark'

urlpatterns = [
    path("", views.BookmarkLV.as_view(), name="index"),
    # 제네릭 뷰는 pk로 받음
    path("<int:pk>/", views.BookmarkDV.as_view(), name="detail"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from config.views import HomeView, UserCreateView, UserCreateDoneTV
from django.conf.urls.static import static
from django.conf import settings
from config.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path('admin/', admin.site.urls),
    path("bookmark/", include("bookmark.urls")),
    path("blog/", include("blog.urls")),
    path("photo/", include("photo.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/register/", UserCreateView.as_view(), name='register'),
    path('accounts/register/done/',UserCreateDoneTV.as_view(), name='register_done'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

photo/urls.py
from django.urls import path

from . import views

app_name = "photo"

urlpatterns = [
    path("", views.AlbumLV.as_view(), name="index"),
    path("album", views.AlbumLV.as_view(), name="album_list"),
    # 제네릭뷰는 pk로 값 찾는게 기본값
    path("album/<int:pk>", views.AlbumDV.as_view(), name="album_detail"),
    path("photo/<int:pk>", views.PhotoDV.as_view(), name="photo_detail"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Like Lion {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% block extra-style %}{% endblock %}
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-secondary" data-bs-theme="dark">
        <div class="container-fluid">
          <a class="navbar-brand mx-5 mb-20 fw-bold fst-italic" href="{% url 'home' %}">Python Web Programming</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'bookmark:index' %}">Bookmark</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'blog:index' %}">Blog</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'photo:index' %}">Photo</a>
              </li>              
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Util
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a></li>
                  <li><a class="dropdown-item" href="{% url 'blog:post_archive' %}">Archive</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'blog:search' %}">Search</a></li>
                </ul>
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
            
            <ul class="navbar-nav ml-5 mr-5">
                <li class="nav-item dropdown mx-1 btn btn-primary">
                    {% if user.is_active %}
                    <a class="nav-link dropdown-toggle text-white" href="#" data-bs-toggle="dropdown">
                      <i class="fas fa-user"></i>&ensp;{% firstof user.get_short_name user.get_username %}&ensp;</a>
                    <div class="dropdown-menu">
                        <form action="{% url 'logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="dropdown-item" >Logout</button>
                        </form>
                      <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
                    </div>
                    {% else %}
                    <a class="nav-link dropdown-toggle text-white" href="#" data-bs-toggle="dropdown">
                      <i class="fas fa-user"></i>&ensp;Anonymous&ensp;</a>
                    <ul class="dropdown-menu">
                      <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                      <a class="dropdown-item" href="{% url 'register' %}">Register</a>
                    </ul>
                    {% endif %}
                </li>
            </ul>

          </div>
        </div>
      </nav>

    <div class="container">
        {% block content %}{% endblock %}
    </div>

    {% block footer %}
    <div class="container text-center fixed-bottom">
        <p>© 2024 재밌는 장고 공부. 모든 권리 보유.</p>
        <p>Follow us: <a href="#">Facebook</a> | <a href="#">Twitter</a> | <a href="#">Instagram</a></p>
        <div class="container">
            <p>개인정보처리방침 | 이용약관</p>
        </div>
    </div> 
    {% endblock %}

    <script src="https://kit.fontawesome.com/c998a172fe.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    {% block extra-script %}{% endblock %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}재밌는 장고 공부{% endblock %}

{% block extra-style %}
<style type="text/css">
    .home-image {
        background-image: url("{% static 'img/image.png' %}");
        background-repeat: no-repeat;
        background-position: center;
        background-size: 100%;
        height: 500px;
        border-top: 10px solid #ccc;
        border-bottom: 10px solid #ccc;
        padding: 20px 0 0 20px;
    }
    .title {
        color: #c80;
        font-weight: bold;
    }
    .powered {
        position: relative;
        top: 77%;
        color: #cc0;
        font-style: italic;
    }
    </style>
{% endblock %}

{% block content %}
<div class="home-image">
    <h2 class="title">Python Web Programming</h2>
</div>

<div class="row text-center">
    <div class="col-sm-6">
        <h3>Bookmark App</h3>
        <p class=fw-light>
            Bookmark is a Uniform Resource Identifier (URI)
                that is stored for later retrieval in any of various storage formats.
                You can store your own bookmarks by Bookmark application.
                It's also possible to update or delete your bookmarks.
        </p>
    </div>
    <div class="col-sm-6">
        <h3>Blog App</h3>
        <p class=fw-light>
            This application makes it possible to log daily events or write your own interests
                such as hobbies, techniques, etc.
                A typical blog combines text, digital images, and links to other blogs, web pages,
                and other media related to its topic.
        </p>
    </div>
</div>
{% endblock %}